/**
 * Mock data para demo de Fase 3 — emula lo que Payload entregará una vez seedeado.
 * Layouts diseñados para hacer match con los Figmas adjuntos:
 *  - caracolNextDemoLayout → screenshot "caracol-next.png"
 *  - dituDemoLayout        → screenshot "ditu.png"
 * Se elimina en Fase 4 cuando las páginas leen desde Payload real.
 */
import type { AnyBlock } from "@/blocks/types";

// ===================================================================
// CARACOL NEXT — `/caracol-next`
// ===================================================================
export const caracolNextDemoLayout: AnyBlock[] = [
  {
    id: "cnx-1",
    blockType: "hero",
    anchorId: "inicio",
    eyebrow: "Donde el contenido conecta",
    heading: "Nuestro ecosistema digital al servicio de tu marca.",
    subheading: "Vamos más allá de la pauta tradicional.",
    keyStats: [],
    brandIcons: [
      { brand: "caracoltv", icon: undefined as never, id: "bi-1" },
      { brand: "golcaracol", icon: undefined as never, id: "bi-2" },
      { brand: "caracolsports", icon: undefined as never, id: "bi-3" },
      { brand: "ditu", icon: undefined as never, id: "bi-4" },
      { brand: "bluradio", icon: undefined as never, id: "bi-5" },
      { brand: "lakalle", icon: undefined as never, id: "bi-6" },
      { brand: "volk", icon: undefined as never, id: "bi-7" },
      { brand: "bumbox", icon: undefined as never, id: "bi-8" },
    ],
    backgroundImage: null,
    backgroundVideo: null,
    primaryCta: {
      label: "Conoce más",
      href: "#audiencia",
      variant: "default",
      openInNewTab: false,
    },
    secondaryCta: { label: "", href: "", variant: "outline", openInNewTab: false },
    tone: "caracolnext-deep",
    blockName: "Hero Caracol Next",
  },
  {
    id: "cnx-2",
    blockType: "audience-networks",
    anchorId: "audiencia",
    eyebrow: "El ecosistema",
    heading: "Nuestro Alcance",
    description: undefined,
    audience: {
      reach: 16_943_700,
      reachLabel: "Usuarios mensuales",
      reachSuffix: null,
      breakdown: [
        { id: "b1", label: "LIDERAZGO | Unidad digital Colombia", value: 1, suffix: "" },
        {
          id: "b2",
          label: "ALCANCE COLOMBIA | 3 de cada 10 colombianos conectados",
          value: 30.2,
          suffix: "%",
        },
        {
          id: "b3",
          label: "TIEMPO | Minutos consumidos",
          value: 248_000_000,
          suffix: "",
        },
        { id: "b4", label: "CONTENIDO | Vistas/mes", value: 84_100_000, suffix: "" },
      ],
    },
    networks: [
      {
        id: "n1",
        network: "facebook",
        handle: "Caracol Next",
        followers: 30_500_000,
        growth: 0,
        url: null,
      },
      {
        id: "n2",
        network: "tiktok",
        handle: "@caracolnext",
        followers: 18_400_000,
        growth: 0,
        url: null,
      },
      {
        id: "n3",
        network: "x",
        handle: "@caracolnext",
        followers: 14_900_000,
        growth: 0,
        url: null,
      },
      {
        id: "n4",
        network: "youtube",
        handle: "Caracol Next",
        followers: 30_500_000,
        growth: 0,
        url: null,
      },
      {
        id: "n5",
        network: "instagram",
        handle: "@caracolnext",
        followers: 22_300_000,
        growth: 0,
        url: null,
      },
      {
        id: "n6",
        network: "threads",
        handle: "@caracolnext",
        followers: 11_100_000,
        growth: 0,
        url: null,
      },
    ],
    highlightedNetwork: null,
    blockName: null,
  },
  {
    id: "cnx-3",
    blockType: "brand-tabs",
    anchorId: "marcas",
    eyebrow: "El ecosistema Caracol",
    heading: "Una marca para cada audiencia",
    description: undefined,
    tabs: [
      {
        brand: "caracoltv",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#015BC4",
        whyChoose: null,
        audience: {
          reach: 3_076_977,
          reachLabel: "Usuarios/mes",
          reachSuffix: null,
          highlights: [
            { id: "h1", value: "11.803.973", valueSuffix: null, label: "Vistas/mes" },
          ],
        },
        networks: [
          {
            id: "ctv-n1",
            network: "facebook",
            handle: null,
            followers: 17_821_911,
            url: null,
          },
          {
            id: "ctv-n2",
            network: "instagram",
            handle: null,
            followers: 3_543_872,
            url: null,
          },
          {
            id: "ctv-n3",
            network: "tiktok",
            handle: null,
            followers: 3_894_409,
            url: null,
          },
          {
            id: "ctv-n4",
            network: "youtube",
            handle: null,
            followers: 8_942_899,
            url: null,
          },
        ],
        adFormats: [],
        ctaContact: {
          label: "Conoce más",
          href: "#contacto",
          variant: "default",
          openInNewTab: false,
        },
        id: "tab-ctv",
      },
      {
        brand: "golcaracol",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#00C853",
        whyChoose: null,
        audience: {
          reach: 11_500_000,
          reachLabel: "Aficionados",
          reachSuffix: null,
          highlights: [],
        },
        networks: [],
        adFormats: [],
        ctaContact: { label: "", href: "" },
        id: "tab-gol",
      },
      {
        brand: "caracolsports",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#FF6F00",
        whyChoose: null,
        audience: {
          reach: 4_500_000,
          reachLabel: "Fans deportes",
          reachSuffix: null,
          highlights: [],
        },
        networks: [],
        adFormats: [],
        ctaContact: { label: "", href: "" },
        id: "tab-sports",
      },
      {
        brand: "bluradio",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#1976D2",
        whyChoose: null,
        audience: {
          reach: 2_800_000,
          reachLabel: "Oyentes",
          reachSuffix: null,
          highlights: [],
        },
        networks: [],
        adFormats: [],
        ctaContact: { label: "", href: "" },
        id: "tab-blu",
      },
      {
        brand: "lakalle",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#FF1744",
        whyChoose: null,
        audience: {
          reach: 1_900_000,
          reachLabel: "Oyentes urbanos",
          reachSuffix: null,
          highlights: [],
        },
        networks: [],
        adFormats: [],
        ctaContact: { label: "", href: "" },
        id: "tab-kalle",
      },
      {
        brand: "bumbox",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#FFC200",
        whyChoose: null,
        audience: {
          reach: 800_000,
          reachLabel: "Audiencia comercio",
          reachSuffix: null,
          highlights: [],
        },
        networks: [],
        adFormats: [],
        ctaContact: { label: "", href: "" },
        id: "tab-bum",
      },
      {
        brand: "volk",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#00B8D4",
        whyChoose: null,
        audience: {
          reach: 600_000,
          reachLabel: "Audiencia",
          reachSuffix: null,
          highlights: [],
        },
        networks: [],
        adFormats: [],
        ctaContact: { label: "", href: "" },
        id: "tab-volk",
      },
    ],
    defaultTab: 0,
    blockName: null,
  },
  {
    id: "cnx-4",
    blockType: "key-moments",
    anchorId: "momentos",
    eyebrow: null,
    heading: "Calendario",
    description: "Los grandes momentos del año, una oportunidad para tu marca.",
    events: [
      {
        id: "e1",
        name: "Año Nuevo",
        dateStart: "2026-01-01",
        dateEnd: null,
        description: "Apertura del año, buenos deseos.",
        image: null,
        importance: "high",
        category: "special",
        cta: { label: "", href: "" },
      },
      {
        id: "e2",
        name: "Carnaval de Barranquilla",
        dateStart: "2026-02-13",
        dateEnd: "2026-02-17",
        description: "Celebraciones · Costumbres · Folclore.",
        image: null,
        importance: "critical",
        category: "entertainment",
        cta: { label: "", href: "" },
      },
      {
        id: "e3",
        name: "Semana Santa",
        dateStart: "2026-03-29",
        dateEnd: null,
        description: "Turismo y familia.",
        image: null,
        importance: "high",
        category: "special",
        cta: { label: "", href: "" },
      },
      {
        id: "e4",
        name: "Día del Niño",
        dateStart: "2026-04-26",
        dateEnd: null,
        description: "Audiencia familiar.",
        image: null,
        importance: "medium",
        category: "entertainment",
        cta: { label: "", href: "" },
      },
      {
        id: "e5",
        name: "FilBo 2026",
        dateStart: "2026-04-29",
        dateEnd: "2026-05-09",
        description: "Libros y lectores.",
        image: null,
        importance: "medium",
        category: "special",
        cta: { label: "", href: "" },
      },
      {
        id: "e6",
        name: "Mundial / Eurocopa",
        dateStart: "2026-06-11",
        dateEnd: "2026-07-19",
        description: "Pasión deportiva.",
        image: null,
        importance: "critical",
        category: "sports",
        cta: { label: "", href: "" },
      },
      {
        id: "e7",
        name: "Halloween",
        dateStart: "2026-10-31",
        dateEnd: null,
        description: "Entretenimiento y consumo.",
        image: null,
        importance: "medium",
        category: "entertainment",
        cta: { label: "", href: "" },
      },
      {
        id: "e8",
        name: "Día de la Independencia",
        dateStart: "2026-07-20",
        dateEnd: null,
        description: "Conmemoración nacional.",
        image: null,
        importance: "high",
        category: "news",
        cta: { label: "", href: "" },
      },
      {
        id: "e9",
        name: "Black Friday",
        dateStart: "2026-11-27",
        dateEnd: null,
        description: "Comercio digital.",
        image: null,
        importance: "high",
        category: "special",
        cta: { label: "", href: "" },
      },
      {
        id: "e10",
        name: "Vuelta a clases",
        dateStart: "2026-01-20",
        dateEnd: null,
        description: "Educación y economía familiar.",
        image: null,
        importance: "medium",
        category: "news",
        cta: { label: "", href: "" },
      },
      {
        id: "e11",
        name: "Amor y amistad",
        dateStart: "2026-09-19",
        dateEnd: null,
        description: "Pico de gifting.",
        image: null,
        importance: "medium",
        category: "entertainment",
        cta: { label: "", href: "" },
      },
      {
        id: "e12",
        name: "Año nuevo",
        dateStart: "2026-12-31",
        dateEnd: "2027-01-01",
        description: "Nuevos comienzos y balances.",
        image: null,
        importance: "high",
        category: "special",
        cta: { label: "", href: "" },
      },
    ],
    displayMode: "grid",
    blockName: null,
  },
  {
    id: "cnx-5",
    blockType: "branded-content",
    anchorId: "branded",
    eyebrow: "Branded Content",
    heading: "Video Podcast",
    description:
      "Domina el formato con mayor retención del entorno digital. Ofrecemos dos soluciones estratégicas: el desarrollo de producciones exclusivas alineadas al ADN de tu marca, o la integración orgánica en nuestros espacios ya posicionados para aprovechar su influencia y alcance.",
    items: [
      {
        id: "bc1",
        eyebrow: "Branded Content",
        headline: "Branded Content: Eduardo Lora · Casos reales",
        description: "Producción exclusiva alineada al ADN de la marca.",
        image: undefined as never,
        href: null,
        brand: "caracoltv",
      },
      {
        id: "bc2",
        eyebrow: "Video Podcast",
        headline: "Video Podcast: Conversaciones cero pauta",
        description: "Integración orgánica en espacios posicionados.",
        image: undefined as never,
        href: null,
        brand: "caracoltv",
      },
      {
        id: "bc3",
        eyebrow: "Producción Comercial",
        headline: "Producción Comercial: Spots de marca",
        description: "Producciones de alto valor para tu campaña.",
        image: undefined as never,
        href: null,
        brand: "caracoltv",
      },
      {
        id: "bc4",
        eyebrow: "Contenido Editorial",
        headline: "Contenido Editorial: Artículos patrocinados",
        description: "Contenido editorial integrado a la línea informativa.",
        image: undefined as never,
        href: null,
        brand: "caracoldigital",
      },
    ],
    layout: "grid",
    blockName: null,
  },
  {
    id: "cnx-6",
    blockType: "ad-formats",
    anchorId: "pauta",
    eyebrow: "Pauta Digital",
    heading: "Llega a millones de colombianos",
    description:
      "Con los formatos publicitarios del ecosistema digital más grande del país.",
    formats: [
      {
        id: "f1",
        name: "Display tradicional y tomas",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f2",
        name: "Intersticial",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f3",
        name: "Sticky",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f4",
        name: "Overlay",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f5",
        name: "Banner Slider",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f6",
        name: "Especie en RRSS",
        brand: null,
        category: "branded",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f7",
        name: "Video Banner",
        brand: null,
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f8",
        name: "Pre-Roll Video",
        brand: null,
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f9",
        name: "Oai Corte Comercial",
        brand: null,
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "f10",
        name: "Prebroll y Midroll Audio",
        brand: null,
        category: "audio",
        image: null,
        specs: null,
        downloadUrl: null,
      },
    ],
    displayMode: "grid",
    filtersEnabled: false,
    blockName: null,
  },
  {
    id: "cnx-7",
    blockType: "contact",
    anchorId: "contacto",
    eyebrow: null,
    heading: "Con nosotros, lleva tu marca al siguiente nivel.",
    description:
      "Cuéntanos tus objetivos y armemos juntos la mejor estrategia para conectar tu marca con millones de colombianos.",
    form: null,
    representatives: [
      {
        id: "r1",
        name: "Daniela Forero",
        role: "Ejecutiva senior",
        email: "dforero@caracoltv.com.co",
        whatsapp: "573001234567",
        photo: null,
      },
      {
        id: "r2",
        name: "Carlos Méndez",
        role: "Brand partnerships",
        email: "cmendez@caracoltv.com.co",
        whatsapp: "573009876543",
        photo: null,
      },
      {
        id: "r3",
        name: "Andrea Vargas",
        role: "Pauta digital",
        email: "avargas@caracoltv.com.co",
        whatsapp: "573005551234",
        photo: null,
      },
    ],
    layout: "reps-only",
    blockName: null,
  },
];

// ===================================================================
// DITU — `/ditu`
// ===================================================================
export const dituDemoLayout: AnyBlock[] = [
  {
    id: "d1",
    blockType: "hero",
    anchorId: "inicio",
    eyebrow: "Ditu",
    heading: "TU MARCA EN TODAS LAS PANTALLAS, EN TODO MOMENTO",
    subheading:
      "Conecta con audiencias TV y app integrada en todos los dispositivos: lleva tu marca al siguiente nivel del entretenimiento conectado.",
    keyStats: [],
    brandIcons: [],
    backgroundImage: null,
    backgroundVideo: null,
    primaryCta: {
      label: "Contáctanos",
      href: "#contacto",
      variant: "brand-ditu",
      openInNewTab: false,
    },
    secondaryCta: {
      label: "App Ditu",
      href: "#",
      variant: "outline",
      openInNewTab: false,
    },
    tone: "ditu-deep",
    blockName: null,
  },
  {
    id: "d2",
    blockType: "audience-networks",
    anchorId: "cifras",
    eyebrow: "Las cifras que mueven a Ditu",
    heading: "Cada mes, millones de pantallas prendidas.",
    description: null,
    audience: {
      reach: 10_717_937,
      reachLabel: "TVs conectadas activas",
      reachSuffix: null,
      breakdown: [
        { id: "db1", label: "STREAMING USERS", value: 3_039_409, suffix: "" },
        { id: "db2", label: "TVS CONECTADAS", value: 474_339, suffix: "" },
        {
          id: "db3",
          label: "WATCH TIME PROMEDIO | minutos/sesión",
          value: 60,
          suffix: " min",
        },
        {
          id: "db4",
          label: "PANTALLAS ÚNICAS | activas/mes",
          value: 3_000_000,
          suffix: "",
        },
      ],
    },
    networks: [
      {
        id: "dn1",
        network: "instagram",
        handle: "@diturl",
        followers: 1_200_000,
        growth: 18.4,
        url: null,
      },
      {
        id: "dn2",
        network: "tiktok",
        handle: "@diturl",
        followers: 2_400_000,
        growth: 28.0,
        url: null,
      },
      {
        id: "dn3",
        network: "youtube",
        handle: "Ditu",
        followers: 3_600_000,
        growth: 12.1,
        url: null,
      },
      {
        id: "dn4",
        network: "facebook",
        handle: "Ditu",
        followers: 1_400_000,
        growth: 6.2,
        url: null,
      },
      {
        id: "dn5",
        network: "threads",
        handle: "@diturl",
        followers: 320_000,
        growth: 45.2,
        url: null,
      },
      {
        id: "dn6",
        network: "x",
        handle: "@diturl",
        followers: 280_000,
        growth: 9.1,
        url: null,
      },
    ],
    highlightedNetwork: "tiktok",
    blockName: null,
  },
  {
    id: "d-adn",
    blockType: "audience-profile",
    anchorId: "adn",
    eyebrow: "ADN Ditu",
    heading: "Sabemos a quién le hablas.",
    description: null,
    genderSplit: {
      femalePercent: 52,
      femaleLabel: "Mujeres",
      maleLabel: "Hombres",
    },
    ageBars: [
      { id: "ab1", label: "TV", value: 52, suffix: "min" },
      { id: "ab2", label: "Móvil", value: 32, suffix: "min" },
      { id: "ab3", label: "Conectado", value: 28, suffix: "min" },
      { id: "ab4", label: "Web", value: 25, suffix: "min" },
    ],
    footnote: "● Fuente: Internas Ditu, abril 2026",
    blockName: null,
  },
  {
    id: "d-donde",
    blockType: "estratos",
    anchorId: "donde",
    eyebrow: "Y dónde encontrarlo",
    heading:
      "El nivel socioeconómico de las audiencias Ditu, en línea con las marcas con más confianza del país.",
    description: null,
    items: [
      { id: "es1", label: "Estrato 1 a 2", value: 22.7, suffix: "%", hint: null },
      { id: "es2", label: "Estrato 3", value: 37.8, suffix: "%", hint: null },
      { id: "es3", label: "Estrato 4", value: 28.9, suffix: "%", hint: null },
      { id: "es4", label: "Estrato 5 a 6", value: 10.6, suffix: "%", hint: null },
    ],
    footnote: "● Fuente: DANE 2024",
    blockName: null,
  },
  {
    id: "d-contenido",
    blockType: "content-type",
    anchorId: "tipo-contenido",
    eyebrow: "Tipo de contenido",
    heading: "Tres formas de habitar la pantalla.",
    description:
      "Estudios digitales con una respuesta del 32.1%, evidencia el calidad y al cubrimiento que cada formato necesita para conectar y entrenar a tu audiencia.",
    types: [
      {
        id: "ct1",
        label: "FAST",
        description:
          "Canales lineales gratuitos con publicidad. Programación 24/7 sin suscripción.",
      },
      {
        id: "ct2",
        label: "Simulcasts",
        description:
          "Transmisión simultánea de la señal lineal con audiencia digital activa.",
      },
      {
        id: "ct3",
        label: "En vivo",
        description: "Eventos exclusivos con audiencia concentrada en tiempo real.",
      },
      {
        id: "ct4",
        label: "VOD / Catchup",
        description:
          "Contenido a demanda y catchup en cualquier dispositivo, en cualquier momento.",
      },
    ],
    defaultIndex: 1,
    blockName: null,
  },
  {
    id: "d3",
    blockType: "our-channels",
    anchorId: "canales",
    eyebrow: "Nuestros canales",
    heading: "Cada audiencia tiene su espacio",
    description: "La toya de tu equipo está aquí.",
    channels: [
      {
        id: "ch1",
        name: "Caracol Televisión",
        description: null,
        color: "#015BC4",
        href: null,
        category: "entretenimiento",
        audienceSize: 850_000,
        logo: null,
      },
      {
        id: "ch2",
        name: "Gol Caracol",
        description: null,
        color: "#00C853",
        href: null,
        category: "deportes",
        audienceSize: 950_000,
        logo: null,
      },
      {
        id: "ch3",
        name: "Caracol Sports",
        description: null,
        color: "#FF6F00",
        href: null,
        category: "deportes",
        audienceSize: 600_000,
        logo: null,
      },
      {
        id: "ch4",
        name: "Mundo Caracol Mundo",
        description: null,
        color: "#8232F0",
        href: null,
        category: "entretenimiento",
        audienceSize: 420_000,
        logo: null,
      },
      {
        id: "ch5",
        name: "BluRadio",
        description: null,
        color: "#1976D2",
        href: null,
        category: "noticias",
        audienceSize: 380_000,
        logo: null,
      },
      {
        id: "ch6",
        name: "Caracol Online",
        description: null,
        color: "#003CCA",
        href: null,
        category: "entretenimiento",
        audienceSize: 510_000,
        logo: null,
      },
      {
        id: "ch7",
        name: "Cargol Online",
        description: null,
        color: "#A139C6",
        href: null,
        category: "entretenimiento",
        audienceSize: 290_000,
        logo: null,
      },
      {
        id: "ch8",
        name: "Mundo Ditu",
        description: null,
        color: "#77EDED",
        href: null,
        category: "entretenimiento",
        audienceSize: 1_100_000,
        logo: null,
      },
    ],
    layout: "grid",
    blockName: null,
  },
  {
    id: "d4",
    blockType: "key-moments",
    anchorId: "momentos",
    eyebrow: "Calendario",
    heading: "Esto se viene",
    description: "Los momentos clave de la pauta por venir.",
    events: [
      {
        id: "dm1",
        name: "FilBo 2026",
        dateStart: "2026-04-29",
        dateEnd: "2026-05-09",
        description: "Libros y lectores.",
        image: null,
        importance: "medium",
        category: "special",
        cta: { label: "", href: "" },
      },
      {
        id: "dm2",
        name: "Carnaval de Barranquilla",
        dateStart: "2026-02-13",
        dateEnd: "2026-02-17",
        description: "Tradición + entretenimiento.",
        image: null,
        importance: "high",
        category: "entertainment",
        cta: { label: "", href: "" },
      },
      {
        id: "dm3",
        name: "Mundial / Eurocopa",
        dateStart: "2026-06-11",
        dateEnd: "2026-07-19",
        description: "Mes de pasión deportiva.",
        image: null,
        importance: "critical",
        category: "sports",
        cta: { label: "", href: "" },
      },
      {
        id: "dm4",
        name: "Día de la Independencia",
        dateStart: "2026-07-20",
        dateEnd: null,
        description: "Conmemoración nacional.",
        image: null,
        importance: "high",
        category: "news",
        cta: { label: "", href: "" },
      },
    ],
    displayMode: "grid",
    blockName: null,
  },
  {
    id: "d5",
    blockType: "ad-formats",
    anchorId: "pauta",
    eyebrow: "Impulsa tu marca",
    heading: "Con formatos de alto impacto",
    description:
      "Hablemos por canales digitales o personalizados — TV display, video, audio y patrocinio.",
    formats: [
      {
        id: "df1",
        name: "Pre-Roll 15s",
        brand: "ditu",
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df2",
        name: "Mid-Roll 30s",
        brand: "ditu",
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df3",
        name: "OAI Corte Comercial",
        brand: "ditu",
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df4",
        name: "Audio Pre-Roll",
        brand: "ditu",
        category: "audio",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df5",
        name: "Banner Display Ditu",
        brand: "ditu",
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df6",
        name: "Sponsored Series",
        brand: "ditu",
        category: "sponsorship",
        image: null,
        specs: null,
        downloadUrl: null,
      },
    ],
    displayMode: "vertical-tabs",
    filtersEnabled: false,
    blockName: null,
  },
  {
    id: "d6",
    blockType: "contact",
    anchorId: "contacto",
    eyebrow: null,
    heading: "¿Hablamos? Lleva tu marca al siguiente nivel.",
    description: "Cuéntanos tus objetivos y armemos la estrategia más poderosa.",
    form: null,
    representatives: [
      {
        id: "dr1",
        name: "Mariana López",
        role: "Lead Ditu Sales",
        email: "mlopez@ditu.com.co",
        whatsapp: "573001112233",
        photo: null,
      },
      {
        id: "dr2",
        name: "Sergio Ramírez",
        role: "Branded Content Ditu",
        email: "sramirez@ditu.com.co",
        whatsapp: "573004445566",
        photo: null,
      },
    ],
    layout: "stacked",
    blockName: null,
  },
];

// ===================================================================
// HEADER & FOOTER demo data (consumirá Payload Globals en Fase 4).
// ===================================================================

export const caracolNextHeaderDemo = {
  landing: "caracol-next" as const,
  navAnchors: [
    { label: "Marcas", anchorId: "marcas" },
    { label: "Audiencia", anchorId: "audiencia" },
    { label: "Momentos", anchorId: "momentos" },
    { label: "Pauta", anchorId: "pauta" },
    { label: "Contacto", anchorId: "contacto" },
  ],
  ctaButton: {
    enabled: true,
    label: "Inicio",
    href: "/",
    variant: "outline" as const,
  },
  sticky: true,
};

export const dituHeaderDemo = {
  landing: "ditu" as const,
  navAnchors: [
    { label: "Canales", anchorId: "canales" },
    { label: "Contenido", anchorId: "tipo-contenido" },
    { label: "Momentos", anchorId: "momentos" },
    { label: "Pauta", anchorId: "pauta" },
    { label: "Contacto", anchorId: "contacto" },
  ],
  ctaButton: {
    enabled: true,
    label: "Inicio",
    href: "/",
    variant: "outline" as const,
  },
  sticky: true,
};

export const caracolNextFooterDemo = {
  landing: "caracol-next" as const,
  tagline:
    "El ecosistema digital más grande de Colombia. Tu marca en los contenidos que mueven al país.",
  columns: [
    {
      heading: "Marcas",
      links: [
        { label: "Caracol TV", href: "#marcas" },
        { label: "Gol Caracol", href: "#marcas" },
        { label: "BluRadio", href: "#marcas" },
        { label: "La Kalle", href: "#marcas" },
      ],
    },
    {
      heading: "Pauta",
      links: [
        { label: "Formatos", href: "#pauta" },
        { label: "Branded Content", href: "#branded" },
        { label: "Especificaciones", href: "#pauta" },
      ],
    },
    {
      heading: "Empresa",
      links: [
        { label: "Acerca de", href: "#" },
        { label: "Trabaja con nosotros", href: "#" },
        { label: "Términos", href: "#" },
      ],
    },
    {
      heading: "Contacto",
      links: [
        { label: "Comercial", href: "#contacto" },
        { label: "Prensa", href: "#" },
      ],
    },
  ],
  socialLinks: [
    { network: "facebook", url: "https://facebook.com/caracolnext" },
    { network: "instagram", url: "https://instagram.com/caracolnext" },
    { network: "x", url: "https://x.com/caracolnext" },
    { network: "youtube", url: "https://youtube.com/caracolnext" },
    { network: "tiktok", url: "https://tiktok.com/@caracolnext" },
  ],
  bottomLine: "©2026 Caracol Comercial Digital — Todos los derechos reservados.",
  useWave: false,
  tone: "caracolnext-deep" as const,
};

export const dituFooterDemo = {
  landing: "ditu" as const,
  tagline:
    "Tu marca en todas las pantallas, en todo momento. Entretenimiento y atención real.",
  columns: [
    {
      heading: "Canales",
      links: [
        { label: "Ditu Cine", href: "#canales" },
        { label: "Ditu Series", href: "#canales" },
        { label: "Ditu Deportes", href: "#canales" },
      ],
    },
    {
      heading: "Pauta",
      links: [
        { label: "Formatos", href: "#pauta" },
        { label: "Especificaciones", href: "#pauta" },
      ],
    },
    {
      heading: "Empresa",
      links: [
        { label: "Acerca de Ditu", href: "#" },
        { label: "Términos", href: "#" },
      ],
    },
  ],
  socialLinks: [
    { network: "instagram", url: "https://instagram.com/diturl" },
    { network: "tiktok", url: "https://tiktok.com/@diturl" },
    { network: "youtube", url: "https://youtube.com/ditu" },
    { network: "threads", url: "https://threads.net/@diturl" },
  ],
  bottomLine: "©2026 Ditu por Caracol Comercial Digital.",
  useWave: true,
  tone: "ditu-deep" as const,
};

export const floatingContactDemo = {
  enabled: true,
  buttonLabel: "Quiero pautar",
  buttonIcon: "Sparkles",
  panelHeading: "Habla con nuestro equipo",
  panelDescription:
    "Escríbenos por correo o WhatsApp. Te respondemos en menos de 24 horas.",
  representatives: [
    {
      name: "Daniela Forero",
      role: "Senior accounts",
      email: "dforero@caracoltv.com.co",
      whatsapp: "573001234567",
      photo: null,
    },
    {
      name: "Carlos Méndez",
      role: "Brand partnerships",
      email: "cmendez@caracoltv.com.co",
      whatsapp: "573009876543",
      photo: null,
    },
    {
      name: "Andrea Vargas",
      role: "Digital",
      email: "avargas@caracoltv.com.co",
      whatsapp: "573005551234",
      photo: null,
    },
  ],
  position: "bottom-right" as const,
};
