/**
 * Mock data para demo de Fase 3 — emula lo que Payload entregará una vez seedeado.
 * Layouts diseñados para hacer match con los Figmas adjuntos:
 *  - caracolNextDemoLayout → screenshot "caracol-next.png"
 *  - dituDemoLayout        → screenshot "ditu.png"
 * Se elimina en Fase 4 cuando las páginas leen desde Payload real.
 */
import type { AnyBlock } from "@/blocks/types";

// ===================================================================
// CARACOL NEXT — `/caracol-next`
// ===================================================================
export const caracolNextDemoLayout: AnyBlock[] = [
  {
    id: "cnx-1",
    blockType: "hero",
    anchorId: "inicio",
    eyebrow: "Donde el contenido conecta",
    // Heading dividido en 2 líneas (Figma): Regular + Bold mismo tamaño 64.
    heading: "Nuestro ecosistema digital al",
    headingBold: "servicio de tu marca.",
    subheading: "Vamos más allá de la pauta tradicional.",
    keyStats: [],
    brandIcons: [
      { brand: "caracoltv", icon: undefined as never, id: "bi-1" },
      { brand: "golcaracol", icon: undefined as never, id: "bi-2" },
      { brand: "caracolsports", icon: undefined as never, id: "bi-3" },
      { brand: "ditu", icon: undefined as never, id: "bi-4" },
      { brand: "bluradio", icon: undefined as never, id: "bi-5" },
      { brand: "lakalle", icon: undefined as never, id: "bi-6" },
      { brand: "volk", icon: undefined as never, id: "bi-7" },
      { brand: "bumbox", icon: undefined as never, id: "bi-8" },
    ],
    backgroundImage: null,
    backgroundVideo: null,
    // Sin CTAs en el Hero: el Figma muestra solo heading + subheading + brand icons.
    primaryCta: { label: "", href: "", variant: "default", openInNewTab: false },
    secondaryCta: { label: "", href: "", variant: "outline", openInNewTab: false },
    tone: "caracolnext-deep",
    blockName: "Hero Caracol Next",
  },
  {
    id: "cnx-2",
    blockType: "audience-networks",
    anchorId: "audiencia",
    eyebrow: "El ecosistema",
    heading: "Nuestro Alcance",
    description: undefined,
    audience: {
      reach: 16_943_700,
      reachLabel: "Usuarios mensuales",
      reachSuffix: null,
      breakdown: [
        { id: "b1", label: "LIDERAZGO | Unidad digital Colombia", value: 1, suffix: "" },
        {
          id: "b2",
          label: "ALCANCE COLOMBIA | 3 de cada 10 colombianos conectados",
          value: 30.2,
          suffix: "%",
        },
        {
          id: "b3",
          label: "TIEMPO | Minutos consumidos",
          value: 248_000_000,
          suffix: "",
        },
        { id: "b4", label: "CONTENIDO | Vistas/mes", value: 84_100_000, suffix: "" },
      ],
    },
    networks: [
      {
        id: "n1",
        network: "facebook",
        handle: "Caracol Next",
        followers: 30_500_000,
        growth: 0,
        url: null,
      },
      {
        id: "n2",
        network: "tiktok",
        handle: "@caracolnext",
        followers: 18_400_000,
        growth: 0,
        url: null,
      },
      {
        id: "n3",
        network: "x",
        handle: "@caracolnext",
        followers: 14_900_000,
        growth: 0,
        url: null,
      },
      {
        id: "n4",
        network: "youtube",
        handle: "Caracol Next",
        followers: 30_500_000,
        growth: 0,
        url: null,
      },
      {
        id: "n5",
        network: "instagram",
        handle: "@caracolnext",
        followers: 22_300_000,
        growth: 0,
        url: null,
      },
      {
        id: "n6",
        network: "threads",
        handle: "@caracolnext",
        followers: 11_100_000,
        growth: 0,
        url: null,
      },
    ],
    highlightedNetwork: null,
    blockName: null,
  },
  {
    id: "cnx-3",
    blockType: "brand-tabs",
    anchorId: "marcas",
    eyebrow: "El ecosistema Caracol",
    // Convención "|" → primera parte Regular, segunda parte Bold (patrón Figma).
    heading: "Una marca para|cada audiencia",
    description: undefined,
    tabs: [
      {
        brand: "caracoltv",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#015BC4",
        tagline: "Referente de entretenimiento y contenido original para todo el país.",
        whyChoose: null,
        webMetrics: {
          usersPerMonth: 3_076_977,
          usersLabel: "Usuarios/mes",
          viewsPerMonth: 11_803_973,
          viewsLabel: "Vistas/mes",
        },
        audience: {
          reach: 3_076_977,
          reachLabel: "Usuarios/mes",
          reachSuffix: null,
          highlights: [],
          genderSplit: {
            femalePercent: 77,
            femaleLabel: "Mujeres",
            maleLabel: "Hombres",
          },
          agePicks: [
            { id: "a1", range: "18-24", value: 32, isPeak: false },
            { id: "a2", range: "25-34", value: 38, isPeak: false },
            { id: "a3", range: "35-44", value: 28, isPeak: false },
            { id: "a4", range: "45-54", value: 35, isPeak: false },
            { id: "a5", range: "55-64", value: 100, isPeak: true },
            { id: "a6", range: "+65", value: 34, isPeak: false },
          ],
          peakAgeRange: "Pico: 55-64 años",
        },
        networks: [
          {
            id: "ctv-n1",
            network: "facebook",
            handle: null,
            followers: 17_821_911,
            url: null,
          },
          {
            id: "ctv-n2",
            network: "instagram",
            handle: null,
            followers: 3_543_872,
            url: null,
          },
          {
            id: "ctv-n3",
            network: "tiktok",
            handle: null,
            followers: 3_894_409,
            url: null,
          },
          {
            id: "ctv-n4",
            network: "youtube",
            handle: null,
            followers: 8_942_899,
            url: null,
          },
          { id: "ctv-n5", network: "x", handle: null, followers: 5_000_000, url: null },
          {
            id: "ctv-n6",
            network: "whatsapp",
            handle: null,
            followers: 381_028,
            url: null,
          },
        ],
        adFormats: [],
        ctaContact: {
          label: "Conoce más",
          href: "#contacto",
          variant: "default",
          openInNewTab: false,
        },
        id: "tab-ctv",
      },
      {
        brand: "golcaracol",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#00C853",
        tagline:
          "La casa del fútbol colombiano — pasión, transmisión y análisis exclusivo.",
        whyChoose: null,
        webMetrics: {
          usersPerMonth: 2_400_000,
          usersLabel: "Usuarios/mes",
          viewsPerMonth: 8_600_000,
          viewsLabel: "Vistas/mes",
        },
        audience: {
          reach: 11_500_000,
          reachLabel: "Aficionados",
          reachSuffix: null,
          highlights: [],
          genderSplit: {
            femalePercent: 28,
            femaleLabel: "Mujeres",
            maleLabel: "Hombres",
          },
          agePicks: [
            { id: "ga1", range: "18-24", value: 60, isPeak: false },
            { id: "ga2", range: "25-34", value: 100, isPeak: true },
            { id: "ga3", range: "35-44", value: 78, isPeak: false },
            { id: "ga4", range: "45-54", value: 50, isPeak: false },
            { id: "ga5", range: "55-64", value: 30, isPeak: false },
            { id: "ga6", range: "+65", value: 20, isPeak: false },
          ],
          peakAgeRange: "Pico: 25-34 años",
        },
        networks: [
          {
            id: "gol-n1",
            network: "facebook",
            handle: null,
            followers: 6_200_000,
            url: null,
          },
          {
            id: "gol-n2",
            network: "instagram",
            handle: null,
            followers: 2_300_000,
            url: null,
          },
          {
            id: "gol-n3",
            network: "tiktok",
            handle: null,
            followers: 3_200_000,
            url: null,
          },
          {
            id: "gol-n4",
            network: "youtube",
            handle: null,
            followers: 1_800_000,
            url: null,
          },
        ],
        adFormats: [],
        ctaContact: {
          label: "Conoce más",
          href: "#contacto",
          variant: "default",
          openInNewTab: false,
        },
        id: "tab-gol",
      },
      {
        brand: "caracolsports",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#FF6F00",
        tagline:
          "Cobertura deportiva multipantalla — fútbol internacional, ciclismo y atletismo.",
        whyChoose: null,
        webMetrics: {
          usersPerMonth: 1_300_000,
          usersLabel: "Usuarios/mes",
          viewsPerMonth: 4_900_000,
          viewsLabel: "Vistas/mes",
        },
        audience: {
          reach: 4_500_000,
          reachLabel: "Fans deportes",
          reachSuffix: null,
          highlights: [],
          genderSplit: {
            femalePercent: 32,
            femaleLabel: "Mujeres",
            maleLabel: "Hombres",
          },
          agePicks: [
            { id: "csa1", range: "18-24", value: 45, isPeak: false },
            { id: "csa2", range: "25-34", value: 90, isPeak: false },
            { id: "csa3", range: "35-44", value: 100, isPeak: true },
            { id: "csa4", range: "45-54", value: 55, isPeak: false },
            { id: "csa5", range: "55-64", value: 28, isPeak: false },
            { id: "csa6", range: "+65", value: 15, isPeak: false },
          ],
          peakAgeRange: "Pico: 35-44 años",
        },
        networks: [
          {
            id: "cs-n1",
            network: "instagram",
            handle: null,
            followers: 980_000,
            url: null,
          },
          { id: "cs-n2", network: "tiktok", handle: null, followers: 720_000, url: null },
          {
            id: "cs-n3",
            network: "youtube",
            handle: null,
            followers: 1_100_000,
            url: null,
          },
          { id: "cs-n4", network: "x", handle: null, followers: 450_000, url: null },
        ],
        adFormats: [],
        ctaContact: {
          label: "Conoce más",
          href: "#contacto",
          variant: "default",
          openInNewTab: false,
        },
        id: "tab-sports",
      },
      {
        brand: "bluradio",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#1976D2",
        tagline:
          "Radio + digital — actualidad, opinión y análisis para la audiencia más informada.",
        whyChoose: null,
        webMetrics: {
          usersPerMonth: 1_800_000,
          usersLabel: "Usuarios/mes",
          viewsPerMonth: 5_400_000,
          viewsLabel: "Vistas/mes",
        },
        audience: {
          reach: 2_800_000,
          reachLabel: "Oyentes",
          reachSuffix: null,
          highlights: [],
          genderSplit: {
            femalePercent: 42,
            femaleLabel: "Mujeres",
            maleLabel: "Hombres",
          },
          agePicks: [
            { id: "ba1", range: "18-24", value: 18, isPeak: false },
            { id: "ba2", range: "25-34", value: 35, isPeak: false },
            { id: "ba3", range: "35-44", value: 65, isPeak: false },
            { id: "ba4", range: "45-54", value: 100, isPeak: true },
            { id: "ba5", range: "55-64", value: 88, isPeak: false },
            { id: "ba6", range: "+65", value: 55, isPeak: false },
          ],
          peakAgeRange: "Pico: 45-54 años",
        },
        networks: [
          {
            id: "blu-n1",
            network: "facebook",
            handle: null,
            followers: 2_400_000,
            url: null,
          },
          {
            id: "blu-n2",
            network: "instagram",
            handle: null,
            followers: 1_100_000,
            url: null,
          },
          { id: "blu-n3", network: "x", handle: null, followers: 920_000, url: null },
          {
            id: "blu-n4",
            network: "youtube",
            handle: null,
            followers: 480_000,
            url: null,
          },
        ],
        adFormats: [],
        ctaContact: {
          label: "Conoce más",
          href: "#contacto",
          variant: "default",
          openInNewTab: false,
        },
        id: "tab-blu",
      },
      {
        brand: "lakalle",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#FF1744",
        tagline: "Música urbana y entretenimiento juvenil 24/7.",
        whyChoose: null,
        webMetrics: {
          usersPerMonth: 1_100_000,
          usersLabel: "Usuarios/mes",
          viewsPerMonth: 3_800_000,
          viewsLabel: "Vistas/mes",
        },
        audience: {
          reach: 1_900_000,
          reachLabel: "Oyentes urbanos",
          reachSuffix: null,
          highlights: [],
          genderSplit: {
            femalePercent: 55,
            femaleLabel: "Mujeres",
            maleLabel: "Hombres",
          },
          agePicks: [
            { id: "la1", range: "18-24", value: 100, isPeak: true },
            { id: "la2", range: "25-34", value: 82, isPeak: false },
            { id: "la3", range: "35-44", value: 40, isPeak: false },
            { id: "la4", range: "45-54", value: 22, isPeak: false },
            { id: "la5", range: "55-64", value: 12, isPeak: false },
            { id: "la6", range: "+65", value: 8, isPeak: false },
          ],
          peakAgeRange: "Pico: 18-24 años",
        },
        networks: [
          {
            id: "lk-n1",
            network: "instagram",
            handle: null,
            followers: 1_800_000,
            url: null,
          },
          {
            id: "lk-n2",
            network: "tiktok",
            handle: null,
            followers: 2_700_000,
            url: null,
          },
          {
            id: "lk-n3",
            network: "youtube",
            handle: null,
            followers: 950_000,
            url: null,
          },
        ],
        adFormats: [],
        ctaContact: {
          label: "Conoce más",
          href: "#contacto",
          variant: "default",
          openInNewTab: false,
        },
        id: "tab-kalle",
      },
      {
        brand: "bumbox",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#FFC200",
        tagline:
          "Marketplace y comercio digital — audiencia transaccional con alta intención.",
        whyChoose: null,
        webMetrics: {
          usersPerMonth: 520_000,
          usersLabel: "Usuarios/mes",
          viewsPerMonth: 1_900_000,
          viewsLabel: "Vistas/mes",
        },
        audience: {
          reach: 800_000,
          reachLabel: "Audiencia comercio",
          reachSuffix: null,
          highlights: [],
          genderSplit: {
            femalePercent: 58,
            femaleLabel: "Mujeres",
            maleLabel: "Hombres",
          },
          agePicks: [
            { id: "bm1", range: "18-24", value: 30, isPeak: false },
            { id: "bm2", range: "25-34", value: 75, isPeak: false },
            { id: "bm3", range: "35-44", value: 100, isPeak: true },
            { id: "bm4", range: "45-54", value: 68, isPeak: false },
            { id: "bm5", range: "55-64", value: 35, isPeak: false },
            { id: "bm6", range: "+65", value: 12, isPeak: false },
          ],
          peakAgeRange: "Pico: 35-44 años",
        },
        networks: [
          {
            id: "bb-n1",
            network: "instagram",
            handle: null,
            followers: 380_000,
            url: null,
          },
          {
            id: "bb-n2",
            network: "facebook",
            handle: null,
            followers: 240_000,
            url: null,
          },
          { id: "bb-n3", network: "tiktok", handle: null, followers: 110_000, url: null },
        ],
        adFormats: [],
        ctaContact: {
          label: "Conoce más",
          href: "#contacto",
          variant: "default",
          openInNewTab: false,
        },
        id: "tab-bum",
      },
      {
        brand: "volk",
        displayName: null,
        brandLogo: undefined as never,
        brandColor: "#00B8D4",
        tagline: "Lifestyle, cultura pop y contenido nicho para audiencia urbana.",
        whyChoose: null,
        webMetrics: {
          usersPerMonth: 380_000,
          usersLabel: "Usuarios/mes",
          viewsPerMonth: 1_200_000,
          viewsLabel: "Vistas/mes",
        },
        audience: {
          reach: 600_000,
          reachLabel: "Audiencia",
          reachSuffix: null,
          highlights: [],
          genderSplit: {
            femalePercent: 48,
            femaleLabel: "Mujeres",
            maleLabel: "Hombres",
          },
          agePicks: [
            { id: "vk1", range: "18-24", value: 85, isPeak: false },
            { id: "vk2", range: "25-34", value: 100, isPeak: true },
            { id: "vk3", range: "35-44", value: 60, isPeak: false },
            { id: "vk4", range: "45-54", value: 28, isPeak: false },
            { id: "vk5", range: "55-64", value: 12, isPeak: false },
            { id: "vk6", range: "+65", value: 6, isPeak: false },
          ],
          peakAgeRange: "Pico: 25-34 años",
        },
        networks: [
          {
            id: "vk-n1",
            network: "instagram",
            handle: null,
            followers: 280_000,
            url: null,
          },
          { id: "vk-n2", network: "tiktok", handle: null, followers: 410_000, url: null },
          { id: "vk-n3", network: "youtube", handle: null, followers: 95_000, url: null },
        ],
        adFormats: [],
        ctaContact: {
          label: "Conoce más",
          href: "#contacto",
          variant: "default",
          openInNewTab: false,
        },
        id: "tab-volk",
      },
    ],
    defaultTab: 0,
    blockName: null,
  },
  {
    id: "cnx-4",
    blockType: "key-moments",
    anchorId: "momentos",
    eyebrow: null,
    heading: "Calendario",
    description: "Los grandes momentos del año, una oportunidad para tu marca.",
    events: [
      // Fila 1
      {
        id: "e1",
        name: "Año Nuevo",
        dateStart: "2026-01-01",
        dateEnd: null,
        dateLabelOverride: "ENE",
        description: "Apertura del año, balances",
        image: null,
        importance: "high",
        category: "special",
        badgeColor: "#015BC4",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e2",
        name: "Carnaval de Barranquilla",
        dateStart: "2026-03-13",
        dateEnd: "2026-03-17",
        dateLabelOverride: "DEL 13 AL 17 DE MARZO",
        description:
          "Celebraciones Celebraciones Celebraciones Celebraciones Celebraciones Celebraciones Celebraciones Celebraciones Celebraciones",
        image: null,
        importance: "critical",
        category: "entertainment",
        badgeColor: "#0D3AA0",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e3",
        name: "Semana Santa",
        dateStart: "2026-03-29",
        dateEnd: null,
        dateLabelOverride: "MARZO",
        description: "Turismo y familia",
        image: null,
        importance: "high",
        category: "special",
        badgeColor: "#FFC200",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e4",
        name: "Día del niño",
        dateStart: "2026-04-26",
        dateEnd: null,
        dateLabelOverride: "ABR",
        description: "Audiencia familiar",
        image: null,
        importance: "medium",
        category: "entertainment",
        badgeColor: "#A139C6",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      // Fila 2
      {
        id: "e5",
        name: "FilBo 2026",
        dateStart: "2026-04-29",
        dateEnd: "2026-05-04",
        dateLabelOverride: "DEL 06 DE MARZO AL 04 DE MAYO",
        description: "Libros e historias",
        image: null,
        importance: "medium",
        category: "special",
        badgeColor: "#FF0013",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e6",
        name: "Mundial / Eurocopa",
        dateStart: "2026-06-11",
        dateEnd: "2026-07-19",
        dateLabelOverride: "JUN",
        description: "Picos deportivos",
        image: null,
        importance: "critical",
        category: "sports",
        badgeColor: "#015BC4",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e7",
        name: "Halloween",
        dateStart: "2026-10-31",
        dateEnd: null,
        dateLabelOverride: "OCT",
        description: "Entretenimiento y consumo",
        image: null,
        importance: "medium",
        category: "entertainment",
        badgeColor: "#015BC4",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e8",
        name: "Día de la independencia",
        dateStart: "2026-07-20",
        dateEnd: null,
        dateLabelOverride: "20-JUL",
        description: "Conversaiones",
        image: null,
        importance: "high",
        category: "news",
        badgeColor: "#FFC200",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      // Fila 3
      {
        id: "e9",
        name: "Black Fridays",
        dateStart: "2026-11-27",
        dateEnd: null,
        dateLabelOverride: "NOV",
        description: "Comercio digital",
        image: null,
        importance: "high",
        category: "special",
        badgeColor: "#015BC4",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e10",
        name: "Vuelta a clases",
        dateStart: "2026-08-15",
        dateEnd: null,
        dateLabelOverride: "AGO",
        description: "Educación y economía familiar",
        image: null,
        importance: "medium",
        category: "news",
        badgeColor: "#015BC4",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e11",
        name: "Amor y amistad",
        dateStart: "2026-09-19",
        dateEnd: null,
        dateLabelOverride: "SEP",
        description: "Pico de grifting",
        image: null,
        importance: "medium",
        category: "entertainment",
        badgeColor: "#015BC4",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
      {
        id: "e12",
        name: "Año nuevo",
        dateStart: "2026-12-31",
        dateEnd: "2027-01-01",
        dateLabelOverride: "ENE - 2027",
        description: "Nuevos comienzos y balances",
        image: null,
        importance: "high",
        category: "special",
        badgeColor: "#015BC4",
        categoryLabel: "CATEGORÍA",
        cta: { label: "", href: "" },
      },
    ],
    displayMode: "grid",
    ctaText: {
      heading:
        "¡Asegura la presencia de tu marca en los eventos más importantes del país!",
      description: "Contáctanos ahora y diseñemos juntos tu participación.",
      label: "Contáctenos",
      href: "#contacto",
    },
    blockName: null,
  },
  {
    id: "cnx-5",
    blockType: "branded-content",
    anchorId: "branded",
    eyebrow: null,
    // El heading section-level está vacío adrede: cada categoría provee su propio
    // título en la columna izquierda (matching Figma).
    heading: "",
    description: null,
    categories: [
      {
        id: "bc-cat1",
        key: "branded-content",
        label: "Branded Content",
        heading: "Branded Content",
        description:
          "Domina el formato con mayor retención del entorno digital. Ofrecemos dos soluciones estratégicas: el desarrollo de producciones exclusivas alineadas al ADN de tu marca, o la integración orgánica en nuestros espacios ya posicionados para aprovechar su influencia y alcance.",
        multimedia: {
          type: "youtube",
          youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          image: null,
          video: null,
          captionTag: "Video Podcast",
          titleOverlay: "Reel 2025 Caracol Next",
          logoTopLeft: null,
          logoTopRight: null,
        },
        secondaryTabs: [],
      },
      {
        id: "bc-cat2",
        key: "video-podcast",
        label: "Video Podcast",
        heading: "Video Podcast",
        description:
          "Domina el formato con mayor retención del entorno digital. Ofrecemos dos soluciones estratégicas: el desarrollo de producciones exclusivas alineadas al ADN de tu marca, o la integración orgánica en nuestros espacios ya posicionados para aprovechar su influencia y alcance.",
        multimedia: {
          type: "youtube",
          youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          image: null,
          video: null,
          captionTag: "Video Podcast",
          titleOverlay: "Eduardo Lora — Host: Lina Martínez",
          logoTopLeft: null,
          logoTopRight: null,
        },
        secondaryTabs: [
          {
            id: "st-1",
            label: "Realities",
            multimedia: {
              type: "youtube",
              youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
              image: null,
              video: null,
              captionTag: "Reality",
              titleOverlay: "Reality Show",
              logoTopLeft: null,
              logoTopRight: null,
            },
          },
          {
            id: "st-2",
            label: "Series Web",
            multimedia: {
              type: "youtube",
              youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
              image: null,
              video: null,
              captionTag: "Series Web",
              titleOverlay: "Series exclusivas",
              logoTopLeft: null,
              logoTopRight: null,
            },
          },
          {
            id: "st-3",
            label: "Talk Shows",
            multimedia: {
              type: "youtube",
              youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
              image: null,
              video: null,
              captionTag: "Talk Show",
              titleOverlay: "Eduardo Lora",
              logoTopLeft: null,
              logoTopRight: null,
            },
          },
          {
            id: "st-4",
            label: "Lives",
            multimedia: {
              type: "youtube",
              youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
              image: null,
              video: null,
              captionTag: "Live",
              titleOverlay: "Lives Caracol Next",
              logoTopLeft: null,
              logoTopRight: null,
            },
          },
          {
            id: "st-5",
            label: "Documental",
            multimedia: {
              type: "youtube",
              youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
              image: null,
              video: null,
              captionTag: "Documental",
              titleOverlay: "Documental Caracol",
              logoTopLeft: null,
              logoTopRight: null,
            },
          },
        ],
      },
      {
        id: "bc-cat3",
        key: "produccion-comercial",
        label: "Producción Comercial",
        heading: "Producción Comercial",
        description:
          "Producciones de alto valor para tu campaña con la infraestructura técnica y creativa de Caracol Medios. Desde spot tradicional hasta producciones largas.",
        multimedia: {
          type: "youtube",
          youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          image: null,
          video: null,
          captionTag: "Comercial",
          titleOverlay: "Producción Comercial",
          logoTopLeft: null,
          logoTopRight: null,
        },
        secondaryTabs: [],
      },
      {
        id: "bc-cat4",
        key: "contenido-editorial",
        label: "Contenido Editorial",
        heading: "Contenido Editorial",
        description:
          "Artículos, especiales y formatos editoriales integrados a la línea informativa de nuestros portales líderes — alcance real con autoridad de marca.",
        multimedia: {
          type: "youtube",
          youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          image: null,
          video: null,
          captionTag: "Editorial",
          titleOverlay: "Contenido Editorial",
          logoTopLeft: null,
          logoTopRight: null,
        },
        secondaryTabs: [],
      },
    ],
    defaultIndex: 0,
    blockName: null,
  },
  {
    id: "cnx-6",
    blockType: "ad-formats",
    anchorId: "pauta",
    eyebrow: null,
    heading: "Pauta Digital",
    description:
      "Llega a millones de colombianos con los formatos publicitarios del ecosistema digital más grande del país.",
    formats: [
      // Columna Display
      {
        id: "f1",
        name: "Display tradicional y toma",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "Display tradicional y tomas",
          description:
            "Formato display estándar — banners IAB en posiciones top y middle del sitio. Alta visibilidad con tomas full screen.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [
            {
              id: "f1-t1",
              label: "Top Banner",
              image: undefined as never,
              description: "Banner superior visible al cargar la página.",
            },
            {
              id: "f1-t2",
              label: "Toma Full Screen",
              image: undefined as never,
              description: "Toma full screen previo al contenido.",
            },
          ],
        },
      },
      {
        id: "f2",
        name: "Interestitial",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "Interestitial",
          description:
            "Anuncio de pantalla completa que aparece entre navegación de páginas.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [],
        },
      },
      {
        id: "f3",
        name: "Sticky",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "Sticky",
          description:
            "Banner adhesivo que permanece visible al hacer scroll. Alta atención sostenida.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [],
        },
      },
      {
        id: "f4",
        name: "Overlay",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "Overlay",
          description:
            "Capa flotante sobre el contenido — alto impacto visual con interacción opcional.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [],
        },
      },
      {
        id: "f5",
        name: "Banner Slider",
        brand: null,
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "Banners de Alto Impacto",
          description:
            "Formatos interactivos de diseñados para integrar múltiples piezas o imágenes en un único espacio creativo de gran visibilidad.\n\nEsta solución estratégica permite que el usuario interactúe directamente para descubrir información detallada, transformando la pauta en una experiencia de marca.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [
            {
              id: "f5-t1",
              label: "Banner Slider",
              image: undefined as never,
              description:
                "Carrusel de banners de alto impacto — varias piezas en un solo espacio creativo.",
            },
            {
              id: "f5-t2",
              label: "Banner Multigalería",
              image: undefined as never,
              description:
                "Galería multi-banner que el usuario explora con interacción táctil.",
            },
            {
              id: "f5-t3",
              label: "Expandible Roll Over",
              image: undefined as never,
              description:
                "Banner que se expande al hover, revelando contenido extendido sin salir de la página.",
            },
            {
              id: "f5-t4",
              label: "Banner Hover Reveal",
              image: undefined as never,
              description:
                "Banner con capa oculta que se revela en hover — efecto sorpresa de alto recall.",
            },
          ],
        },
      },
      {
        id: "f6",
        name: "Espacio en RRSS",
        brand: null,
        category: "branded",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "Espacio en Redes Sociales",
          description:
            "Pauta integrada en las redes oficiales del ecosistema Caracol — Facebook, Instagram, TikTok, X, YouTube.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [],
        },
      },
      // Columna Video & Audio
      {
        id: "f7",
        name: "Video  Banner",
        brand: null,
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "Video Banner",
          description:
            "Banner con video auto-play silencioso. Alta retención visual sin invadir la experiencia.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [],
        },
      },
      {
        id: "f8",
        name: "Pre-Roll Video",
        brand: null,
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "Pre-Roll Video",
          description:
            "Anuncio de 15s al inicio de cada video del ecosistema. Atención garantizada.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [],
        },
      },
      {
        id: "f9",
        name: "DAI Corte Comercia",
        brand: null,
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "DAI — Corte Comercial",
          description:
            "Dynamic Ad Insertion en cortes comerciales del contenido en vivo y on-demand.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [],
        },
      },
      {
        id: "f10",
        name: "PreRoll y MidRoll Audio",
        brand: null,
        category: "audio",
        image: null,
        specs: null,
        downloadUrl: null,
        modal: {
          title: "PreRoll y MidRoll Audio",
          description:
            "Cuñas pre-roll (antes del contenido) y mid-roll (durante el contenido) en streaming de audio.",
          ctaLabel: "Contáctanos",
          ctaHref: "#contacto",
          childTabs: [],
        },
      },
    ],
    displayMode: "grid",
    filtersEnabled: false,
    footerCta: {
      heading:
        "¡Asegura la presencia de tu marca en los eventos más importantes del país!",
      description: "Contáctanos ahora y diseñemos juntos tu participación.",
      label: "Descargar Especificaciones",
      href: "#contacto",
    },
    blockName: null,
  },
  {
    id: "cnx-7",
    blockType: "contact",
    anchorId: "contacto",
    eyebrow: null,
    heading: "Con nosotros, lleva tu marca",
    headingEmphasis: "al siguiente nivel.",
    description:
      "Cuéntanos tus objetivos y armemos juntos la mejor estrategia para conectar tu marca con millones de colombianos.",
    form: null,
    representatives: [],
    ctaButton: {
      label: "Contáctenos",
      href: "#contacto",
      variant: "default",
      openInNewTab: false,
    },
    layout: "cta-simple",
    blockName: null,
  },
];

// ===================================================================
// DITU — `/ditu`
// ===================================================================
export const dituDemoLayout: AnyBlock[] = [
  {
    id: "d1",
    blockType: "hero",
    anchorId: "inicio",
    eyebrow: "Ditu",
    heading: "TU MARCA EN TODAS LAS PANTALLAS, EN TODO MOMENTO",
    subheading:
      "Conecta con audiencias TV y app integrada en todos los dispositivos: lleva tu marca al siguiente nivel del entretenimiento conectado.",
    keyStats: [],
    brandIcons: [],
    backgroundImage: null,
    backgroundVideo: null,
    primaryCta: {
      label: "Contáctanos",
      href: "#contacto",
      variant: "brand-ditu",
      openInNewTab: false,
    },
    secondaryCta: {
      label: "App Ditu",
      href: "#",
      variant: "outline",
      openInNewTab: false,
    },
    tone: "ditu-deep",
    blockName: null,
  },
  {
    id: "d2",
    blockType: "audience-networks",
    anchorId: "cifras",
    eyebrow: "Las cifras que mueven a Ditu",
    heading: "Cada mes, millones de pantallas prendidas.",
    description: null,
    audience: {
      reach: 10_717_937,
      reachLabel: "TVs conectadas activas",
      reachSuffix: null,
      breakdown: [
        { id: "db1", label: "STREAMING USERS", value: 3_039_409, suffix: "" },
        { id: "db2", label: "TVS CONECTADAS", value: 474_339, suffix: "" },
        {
          id: "db3",
          label: "WATCH TIME PROMEDIO | minutos/sesión",
          value: 60,
          suffix: " min",
        },
        {
          id: "db4",
          label: "PANTALLAS ÚNICAS | activas/mes",
          value: 3_000_000,
          suffix: "",
        },
      ],
    },
    networks: [
      {
        id: "dn1",
        network: "instagram",
        handle: "@diturl",
        followers: 1_200_000,
        growth: 18.4,
        url: null,
      },
      {
        id: "dn2",
        network: "tiktok",
        handle: "@diturl",
        followers: 2_400_000,
        growth: 28.0,
        url: null,
      },
      {
        id: "dn3",
        network: "youtube",
        handle: "Ditu",
        followers: 3_600_000,
        growth: 12.1,
        url: null,
      },
      {
        id: "dn4",
        network: "facebook",
        handle: "Ditu",
        followers: 1_400_000,
        growth: 6.2,
        url: null,
      },
      {
        id: "dn5",
        network: "threads",
        handle: "@diturl",
        followers: 320_000,
        growth: 45.2,
        url: null,
      },
      {
        id: "dn6",
        network: "x",
        handle: "@diturl",
        followers: 280_000,
        growth: 9.1,
        url: null,
      },
    ],
    highlightedNetwork: "tiktok",
    blockName: null,
  },
  {
    id: "d-adn",
    blockType: "audience-profile",
    anchorId: "adn",
    eyebrow: "ADN Ditu",
    heading: "Sabemos a quién le hablas.",
    description: null,
    genderSplit: {
      femalePercent: 52,
      femaleLabel: "Mujeres",
      maleLabel: "Hombres",
    },
    ageBars: [
      { id: "ab1", label: "TV", value: 52, suffix: "min" },
      { id: "ab2", label: "Móvil", value: 32, suffix: "min" },
      { id: "ab3", label: "Conectado", value: 28, suffix: "min" },
      { id: "ab4", label: "Web", value: 25, suffix: "min" },
    ],
    footnote: "● Fuente: Internas Ditu, abril 2026",
    blockName: null,
  },
  {
    id: "d-donde",
    blockType: "estratos",
    anchorId: "donde",
    eyebrow: "Y dónde encontrarlo",
    heading:
      "El nivel socioeconómico de las audiencias Ditu, en línea con las marcas con más confianza del país.",
    description: null,
    items: [
      { id: "es1", label: "Estrato 1 a 2", value: 22.7, suffix: "%", hint: null },
      { id: "es2", label: "Estrato 3", value: 37.8, suffix: "%", hint: null },
      { id: "es3", label: "Estrato 4", value: 28.9, suffix: "%", hint: null },
      { id: "es4", label: "Estrato 5 a 6", value: 10.6, suffix: "%", hint: null },
    ],
    footnote: "● Fuente: DANE 2024",
    blockName: null,
  },
  {
    id: "d-contenido",
    blockType: "content-type",
    anchorId: "tipo-contenido",
    eyebrow: "Tipo de contenido",
    heading: "Tres formas de habitar la pantalla.",
    description:
      "Estudios digitales con una respuesta del 32.1%, evidencia el calidad y al cubrimiento que cada formato necesita para conectar y entrenar a tu audiencia.",
    types: [
      {
        id: "ct1",
        label: "FAST",
        description:
          "Canales lineales gratuitos con publicidad. Programación 24/7 sin suscripción.",
      },
      {
        id: "ct2",
        label: "Simulcasts",
        description:
          "Transmisión simultánea de la señal lineal con audiencia digital activa.",
      },
      {
        id: "ct3",
        label: "En vivo",
        description: "Eventos exclusivos con audiencia concentrada en tiempo real.",
      },
      {
        id: "ct4",
        label: "VOD / Catchup",
        description:
          "Contenido a demanda y catchup en cualquier dispositivo, en cualquier momento.",
      },
    ],
    defaultIndex: 1,
    blockName: null,
  },
  {
    id: "d3",
    blockType: "our-channels",
    anchorId: "canales",
    eyebrow: "Nuestros canales",
    heading: "Cada audiencia tiene su espacio",
    description: "La toya de tu equipo está aquí.",
    channels: [
      {
        id: "ch1",
        name: "Caracol Televisión",
        description: null,
        color: "#015BC4",
        href: null,
        category: "entretenimiento",
        audienceSize: 850_000,
        logo: null,
      },
      {
        id: "ch2",
        name: "Gol Caracol",
        description: null,
        color: "#00C853",
        href: null,
        category: "deportes",
        audienceSize: 950_000,
        logo: null,
      },
      {
        id: "ch3",
        name: "Caracol Sports",
        description: null,
        color: "#FF6F00",
        href: null,
        category: "deportes",
        audienceSize: 600_000,
        logo: null,
      },
      {
        id: "ch4",
        name: "Mundo Caracol Mundo",
        description: null,
        color: "#8232F0",
        href: null,
        category: "entretenimiento",
        audienceSize: 420_000,
        logo: null,
      },
      {
        id: "ch5",
        name: "BluRadio",
        description: null,
        color: "#1976D2",
        href: null,
        category: "noticias",
        audienceSize: 380_000,
        logo: null,
      },
      {
        id: "ch6",
        name: "Caracol Online",
        description: null,
        color: "#003CCA",
        href: null,
        category: "entretenimiento",
        audienceSize: 510_000,
        logo: null,
      },
      {
        id: "ch7",
        name: "Cargol Online",
        description: null,
        color: "#A139C6",
        href: null,
        category: "entretenimiento",
        audienceSize: 290_000,
        logo: null,
      },
      {
        id: "ch8",
        name: "Mundo Ditu",
        description: null,
        color: "#77EDED",
        href: null,
        category: "entretenimiento",
        audienceSize: 1_100_000,
        logo: null,
      },
    ],
    layout: "grid",
    blockName: null,
  },
  {
    id: "d4",
    blockType: "key-moments",
    anchorId: "momentos",
    eyebrow: "Calendario",
    heading: "Esto se viene",
    description: "Los momentos clave de la pauta por venir.",
    events: [
      {
        id: "dm1",
        name: "FilBo 2026",
        dateStart: "2026-04-29",
        dateEnd: "2026-05-09",
        description: "Libros y lectores.",
        image: null,
        importance: "medium",
        category: "special",
        cta: { label: "", href: "" },
      },
      {
        id: "dm2",
        name: "Carnaval de Barranquilla",
        dateStart: "2026-02-13",
        dateEnd: "2026-02-17",
        description: "Tradición + entretenimiento.",
        image: null,
        importance: "high",
        category: "entertainment",
        cta: { label: "", href: "" },
      },
      {
        id: "dm3",
        name: "Mundial / Eurocopa",
        dateStart: "2026-06-11",
        dateEnd: "2026-07-19",
        description: "Mes de pasión deportiva.",
        image: null,
        importance: "critical",
        category: "sports",
        cta: { label: "", href: "" },
      },
      {
        id: "dm4",
        name: "Día de la Independencia",
        dateStart: "2026-07-20",
        dateEnd: null,
        description: "Conmemoración nacional.",
        image: null,
        importance: "high",
        category: "news",
        cta: { label: "", href: "" },
      },
    ],
    displayMode: "grid",
    blockName: null,
  },
  {
    id: "d5",
    blockType: "ad-formats",
    anchorId: "pauta",
    eyebrow: "Impulsa tu marca",
    heading: "Con formatos de alto impacto",
    description:
      "Hablemos por canales digitales o personalizados — TV display, video, audio y patrocinio.",
    formats: [
      {
        id: "df1",
        name: "Pre-Roll 15s",
        brand: "ditu",
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df2",
        name: "Mid-Roll 30s",
        brand: "ditu",
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df3",
        name: "OAI Corte Comercial",
        brand: "ditu",
        category: "video",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df4",
        name: "Audio Pre-Roll",
        brand: "ditu",
        category: "audio",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df5",
        name: "Banner Display Ditu",
        brand: "ditu",
        category: "display",
        image: null,
        specs: null,
        downloadUrl: null,
      },
      {
        id: "df6",
        name: "Sponsored Series",
        brand: "ditu",
        category: "sponsorship",
        image: null,
        specs: null,
        downloadUrl: null,
      },
    ],
    displayMode: "vertical-tabs",
    filtersEnabled: false,
    blockName: null,
  },
  {
    id: "d6",
    blockType: "contact",
    anchorId: "contacto",
    eyebrow: null,
    heading: "¿Hablamos? Lleva tu marca al siguiente nivel.",
    headingEmphasis: null,
    description: "Cuéntanos tus objetivos y armemos la estrategia más poderosa.",
    form: null,
    representatives: [
      {
        id: "dr1",
        name: "Mariana López",
        role: "Lead Ditu Sales",
        email: "mlopez@ditu.com.co",
        whatsapp: "573001112233",
        photo: null,
      },
      {
        id: "dr2",
        name: "Sergio Ramírez",
        role: "Branded Content Ditu",
        email: "sramirez@ditu.com.co",
        whatsapp: "573004445566",
        photo: null,
      },
    ],
    ctaButton: { label: "", href: "" },
    layout: "stacked",
    blockName: null,
  },
];

// ===================================================================
// HEADER & FOOTER demo data (consumirá Payload Globals en Fase 4).
// ===================================================================

export const caracolNextHeaderDemo = {
  landing: "caracol-next" as const,
  navAnchors: [
    { label: "Marcas", anchorId: "marcas" },
    { label: "Audiencia", anchorId: "audiencia" },
    { label: "Momentos", anchorId: "momentos" },
    { label: "Pauta", anchorId: "pauta" },
    { label: "Contacto", anchorId: "contacto" },
  ],
  // Spec: el CTA del navbar redirige a la landing Ditu.
  ctaButton: {
    enabled: true,
    label: "Conoce ditu",
    href: "/ditu",
    variant: "brand-ditu" as const,
  },
  sticky: true,
};

export const dituHeaderDemo = {
  landing: "ditu" as const,
  navAnchors: [
    { label: "Canales", anchorId: "canales" },
    { label: "Contenido", anchorId: "tipo-contenido" },
    { label: "Momentos", anchorId: "momentos" },
    { label: "Pauta", anchorId: "pauta" },
    { label: "Contacto", anchorId: "contacto" },
  ],
  ctaButton: {
    enabled: true,
    label: "Inicio",
    href: "/",
    variant: "outline" as const,
  },
  sticky: true,
};

export const caracolNextFooterDemo = {
  landing: "caracol-next" as const,
  tagline:
    "El ecosistema digital más grande de Colombia. Tu marca en los contenidos que mueven al país.",
  columns: [
    {
      heading: "Marcas",
      links: [
        { label: "Caracol TV", href: "#marcas" },
        { label: "Gol Caracol", href: "#marcas" },
        { label: "BluRadio", href: "#marcas" },
        { label: "La Kalle", href: "#marcas" },
      ],
    },
    {
      heading: "Pauta",
      links: [
        { label: "Formatos", href: "#pauta" },
        { label: "Branded Content", href: "#branded" },
        { label: "Especificaciones", href: "#pauta" },
      ],
    },
    {
      heading: "Empresa",
      links: [
        { label: "Acerca de", href: "#" },
        { label: "Trabaja con nosotros", href: "#" },
        { label: "Términos", href: "#" },
      ],
    },
    {
      heading: "Contacto",
      links: [
        { label: "Comercial", href: "#contacto" },
        { label: "Prensa", href: "#" },
      ],
    },
  ],
  socialLinks: [
    { network: "facebook", url: "https://facebook.com/caracolnext" },
    { network: "instagram", url: "https://instagram.com/caracolnext" },
    { network: "x", url: "https://x.com/caracolnext" },
    { network: "youtube", url: "https://youtube.com/caracolnext" },
    { network: "tiktok", url: "https://tiktok.com/@caracolnext" },
  ],
  bottomLine: "©2026 Caracol Comercial Digital",
  useWave: false,
  // Matching Figma "caracol-next": footer minimal con pill gris al fondo.
  // El cierre rico (heading + CTA) lo provee el ContactBlock con layout="cta-simple".
  tone: "minimal" as const,
};

export const dituFooterDemo = {
  landing: "ditu" as const,
  tagline:
    "Tu marca en todas las pantallas, en todo momento. Entretenimiento y atención real.",
  columns: [
    {
      heading: "Canales",
      links: [
        { label: "Ditu Cine", href: "#canales" },
        { label: "Ditu Series", href: "#canales" },
        { label: "Ditu Deportes", href: "#canales" },
      ],
    },
    {
      heading: "Pauta",
      links: [
        { label: "Formatos", href: "#pauta" },
        { label: "Especificaciones", href: "#pauta" },
      ],
    },
    {
      heading: "Empresa",
      links: [
        { label: "Acerca de Ditu", href: "#" },
        { label: "Términos", href: "#" },
      ],
    },
  ],
  socialLinks: [
    { network: "instagram", url: "https://instagram.com/diturl" },
    { network: "tiktok", url: "https://tiktok.com/@diturl" },
    { network: "youtube", url: "https://youtube.com/ditu" },
    { network: "threads", url: "https://threads.net/@diturl" },
  ],
  bottomLine: "©2026 Ditu por Caracol Comercial Digital.",
  useWave: true,
  tone: "ditu-deep" as const,
};

export const floatingContactDemo = {
  enabled: true,
  buttonLabel: "Quiero pautar",
  buttonIcon: "Sparkles",
  panelHeading: "Habla con nuestro equipo",
  panelDescription:
    "Escríbenos por correo o WhatsApp. Te respondemos en menos de 24 horas.",
  representatives: [
    {
      name: "Daniela Forero",
      role: "Senior accounts",
      email: "dforero@caracoltv.com.co",
      whatsapp: "573001234567",
      photo: null,
    },
    {
      name: "Carlos Méndez",
      role: "Brand partnerships",
      email: "cmendez@caracoltv.com.co",
      whatsapp: "573009876543",
      photo: null,
    },
    {
      name: "Andrea Vargas",
      role: "Digital",
      email: "avargas@caracoltv.com.co",
      whatsapp: "573005551234",
      photo: null,
    },
  ],
  position: "bottom-right" as const,
};
